### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by traday** [traday/irs#1]
Authentication will be token based.

**Comment by traday** [comment]
I will take this.

**Comment by blzabub** [comment]
Hey Tom and rest of collaborators, just wanted to point out that Github issues has an "Assignee" feature. If you look in the right column of the issue view at the top there's an "Assignees" header with a widget control. You can assign issues to other people or to yourself. I've assigned this issue to you. :)

**Comment by traday** [comment]
Perfect!  Thanks Ben.
