### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by traday** [traday/irs#2]
## Description
An admin should be able to Create/Read/Update a user, so we need json endpoints: :index, :create, :update
Update includes disable.
## Attributes for a user:
- last name: string
- first name: string
- email(is login):string,
- password:string (password_digest),
- admin:boolean
- officer:boolean
- disabled:boolean

## rspec request tests for the API:
- get index - Fabricate several users in the DB, they should be returned by the json API.
- post create - Should create a new user. 
- put update - Should update attributes with some exceptions: Admin should not be able to remove admin or disable self.

**Comment by MatthewTFarley** [comment]
@traday do (any/all) `User` fields need to have defaults or `null: false` guards at the database level?

**Comment by traday** [comment]
No.  It should be taken care of at the application layer (validation of not null to for non-boolean fields and defaults of false for boolean fields.

**Comment by MatthewTFarley** [comment]
@traday understood on validating in the model. What about applying defaults? I have always set the column to default to a value in a migration.

**Comment by traday** [comment]
I don't really use default in the DB.  That should all be taken care of by the code.

I merged your changes, thank you!
