### ISSUE TITLE
WIP: Upload Personnel

### ISSUE THREAD

**Issue by traday** [traday/irs#4]
## Description
The personnel for a station should be uploadable from a CSV text file.  There are only three columns, with headers, that we care about (though there may or may not be more columns than 2!) and they will always be the first two columns.  
We will use Ruby's **Base64 module** to decode the string

### Format info

| Name    | Station ID | Membership Category |
| --------| ----------| -----------------------|
| Name | Last First| No middle names, always just two values, last and first. |
| Membership category | random string | No need to separate or parse |

### Sample data

| Name | Station ID | Membership category |
| ------| -----------| -------------| 
| Lodge Veronica | 235 | Fire Police |
| Cooper Betty | 43-1 | FF/EMT |
| Jones Jughead | 787 | C - FF/EMT |
| Mantle Reggie | 336 | Probationary FF |

## Validation
This is pretty simple.  
- First row is the header.  
- All remaining rows have name, station id and category value. (entirely blank rows OK.  Ignore)
- Name Is just a string, may have spaces.  
### Errors
On validation failure, we will return :unprocessable_entity with a text message for the error.  Return up to 3 errors.

### Success
On successful validation, finish processing and return :ok200

## Processing
If the Person does not exist (exact match of both first and last name) add them with the category
If the Person does exist but the category is different, simply update the category.
If both the person and the category exist, ignore.

**Comment by bandrben** [comment]
I think I started discussing this in a different Issue, but same concept here.  We should try to key on member ID number if possible, which it should be possible (all members in our co. have an ID number from "somewhere").

So, you'll be taking a CSV file and converting to base64 and sending to a service somewhere.  Sounds good.

**Comment by traday** [comment]
Yup, we want that id number from IAR.  That was what my email was about, can we trust that data.  It sounds like you are going to clean that up.  Perfect, then we will input that as well.
