### ISSUE TITLE
Upload Personnel

### ISSUE THREAD

**Issue by traday** [traday/irs#5]
## Description
This should be a very simple form.  It takes the location of the file on the browser's computer.  Base64 encodes it and makes a request to the API.  

## Validation errors
It will receive up to 3 errors (return :unprocessable_entity) which need to be displayed at the top of the screen.

## Upon success, the Person List page should be displayed with a success message.

**Comment by bandrben** [comment]
Sounds right, don't have too much input on how the interface handles a file upload.  The service would take the file and then "merge"(?) the changes with the personnel table?  The merge situation will be interesting, trying to match each IAR record with IRS personnel.  Matching on first name and last name, even better would be our co. ID numbers, which would require updating IAR with that info first.  

I think we should get that part of the project done ASAP, updating IAR with the actual co. member ID numbers, which should have been done a long time ago.  We all know our numbers, plus they must be in NFIRS or in our personnel file or somewhere else.  Once those numbers are in IAR we could key on that for sure.

**Comment by traday** [comment]
Agreed, for the most part.  I don't want to do too complex a merge.  We have to trust something (name or IAR Member #) and then everything comes off that.
