### ISSUE TITLE
Add a column to Members for Inactive. Change Index page to allow for edit of this field.

### ISSUE THREAD

**Issue by traday** [traday/irs#53]
Some members will NEVER respond because they have retired or whatever.  They should not appear in the dropdowns on Incident or Responders or in the reports.
With a checkbox that designates them as active or not, we can filter them.
The boolean column will be called inactive.
Inactive = true will prevent the member from appearing in the dropdowns on incident or responders page (that is a separate issue)

**Comment by MatthewTFarley** [comment]
@traday I completed this issue. On the members index page, there is an inactive column with checkboxes. When a box is checked or unchecked, an ajax request is sent to the api/members#update action, toggling the inactive value. No dropdowns were updated to show only active members.

**Comment by traday** [comment]
Very good.  Thanks, Matt.
