### ISSUE TITLE
Personnel list page

### ISSUE THREAD

**Issue by traday** [traday/irs#6]
## Description
We need a table form list page like:  

| Last name | First Name| Category|
| ----- | ---- | -----|
| Lodge | Veronica | Fire Police |
| Cooper | Betty | FF/EMT |
| Jones  | Jughead | C - FF/EMT |
| Mantle | Reggie | Probationary FF |

Sorted by last name ASC, then first ASC.

For Admins, there will be a link to the upload personnel page (or maybe we should have it on the same page?)
For non-admins, no upload link or button.

**Comment by bandrben** [comment]
Why have an interface for personnel?  Isn't that going to be more of a back-end import from IAR situation?  Or do we need it for CRUD too for simple changes?

**Comment by traday** [comment]
This is just a list page, just so we can see what is in the system to double check.  If we want to change something, we change it in IAR, export it and then upload it and check it here.
